### ISSUE TITLE
Split error with GitLab integration

### ISSUE THREAD

**Issue by TipiT** [malko/rocketchat-gitlab-hook#36] opened 2023-04-18 15:47 UTC
Everything seems to work nicely, but it's kind of annoying that with pushes, MR's, and merges I get always an error:

 `Rocket.Cat ErrorHandler
5:37 PM
Error occured while parsing an incoming webhook request. Details attached.
Error: 'TypeError: Cannot read property 'split' of undefined', Message: 'Cannot read property 'split' of undefined', Stack: 'TypeError: Cannot read property 'split' of undefined at Script.systemEvent (script.js:1:12882) at Script.process_incoming_request (script.js:1:3656) at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11) at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11) at Proxy.<anonymous> (vm.js:6:23) at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11)'`

I tried to remove the "split" section, but then I get: 

`Rocket.Cat ErrorHandler
5:08 PM
Error occured while parsing an incoming webhook request. Details attached.
Error: 'TypeError: this.systemEvent is not a function', Message: 'this.systemEvent is not a function', Stack: 'TypeError: this.systemEvent is not a function at Script.process_incoming_request (script.js:1:2186) at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11) at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11) at Proxy.<anonymous> (vm.js:6:23) at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11)'`

Any ideas what that might be?

**Comment by malko** [comment] 2023-04-18 16:33
Can you please try to add the following console.log between lines 54 and 55:
```console.log("Event name", event)```
And report what are the event names you get in the logs for MR/Push/merge because it looks like they are considered as system events instead as what they should be.
I'm sorry but without any install on my side I can't check this myself

**Comment by TipiT** [comment] 2023-04-18 17:32
Hey, thanks for the fast reply!

I added the log and fired a pushed. I got the same error, but nothing in console. Only:

in Firefox:

`
Autoplay is only allowed when approved by the user, the site is activated by the user, or media is muted. [b664a9c37e5eb3b02bef6a9be0fdcddb0fdc7511.js:1636:803333]
(https://xxx.rocket.chat/b664a9c37e5eb3b02bef6a9be0fdcddb0fdc7511.js?meteor_js_resource=true)

Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. 2

Uncaught (in promise) DOMException: The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

Some cookies are misusing the recommended “SameSite“ attribute 2

Cookie “_csrf” has been rejected for invalid domain.
`

and

in Chrome: 

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://gitlab.xxx.com/users/sign_in with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
`

**Comment by malko** [comment] 2023-04-18 17:42
You should look at the log outputs in rocketchat admin

**Comment by TipiT** [comment] 2023-04-19 07:46
Here it goes the last few errors and prints from the "View Logs". I added new lines for readability:

`{"level":40,"time":"2023-04-18T14:12:55.989Z","pid":1,"hostname":"habinator-74cdb5b984-9xzmr","name":"DeprecationWarning","section":"METHOD","msg":"getAvatarSuggestion will be deprecated in future versions of Rocket.Chat"} 

{"level":50,"time":"2023-04-18T14:12:59.399Z","pid":1,"hostname":"habinator-74cdb5b984-9xzmr","name":"System","msg":"Exception while invoking method verifyEmail","err":{"type":"errorClass","message":"E-mail verified [verify-email]","stack":"Error: E-mail verified [verify-email]<br>    at app/2fa/server/loginHandler.ts:30:10<br>    at Callbacks.runOne (lib/callbacks.ts:262:11)<br>    at lib/callbacks.ts:274:17<br>    at lib/callbacks.ts:282:5<br>    at lib/callbacks.ts:290:12<br>    at Callbacks.run (lib/callbacks.ts:402:10)<br>    at app/authentication/server/startup/index.js:362:20<br>    at packages/callback-hook/hook.js:141:18<br>    at packages/accounts-base/accounts_server.js:226:15<br>    at Hook.forEach (packages/callback-hook/hook.js:110:15)<br>    at AccountsServer._validateLogin (packages/accounts-base/accounts_server.js:223:29)<br>    at packages/accounts-base/accounts_server.js:473:10<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at packages/accounts-base/accounts_server.js:505:5<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at packages/accounts-password/password_server.js:745:3<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)<br>    at Server.apply (packages/ddp-server/livedata_server.js:1769:22)<br>    at Server.call (packages/ddp-server/livedata_server.js:1738:17)<br>    at Object.post (app/api/server/v1/misc.ts:612:27)<br>    at app/api/server/api.js:463:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"verify-email","reason":"E-mail verified","errorType":"Meteor.Error"},"msg":"E-mail verified [verify-email]"} 

gitlabevent error TypeError [Error]: Cannot read property 'split' of undefined     at Script.systemEvent (script.js:1:12882)     at Script.process_incoming_request (script.js:1:3656)     at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11)     at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11)     at Proxy.<anonymous> (vm.js:6:23)     at VM2 Wrapper.apply (/app/bundle/programs/server/npm/node_modules/vm2/lib/bridge.js:485:11) {"level":50,"time":"2023-04-18T14:56:51.603Z","pid":1,"hostname":"habinator-74cdb5b984-9xzmr","name":"OEmbed","msg":"Error fetching url content","err":{"type":"FetchError","message":"request to https://xxx.com/project/habinator-professionals/merge_requests/66 failed, reason: unable to verify the first certificate","stack":"FetchError: request to https://xxx.com/project/habinator-professionals/merge_requests/66 failed, reason: unable to verify the first certificate<br>    at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)<br>    at ClientRequest.emit (events.js:400:28)<br>    at ClientRequest.emit (domain.js:475:12)<br>    at TLSSocket.socketErrorListener (_http_client.js:475:9)<br>    at TLSSocket.emit (events.js:400:28)<br>    at TLSSocket.emit (domain.js:475:12)<br>    at emitErrorNT (internal/streams/destroy.js:106:8)<br>    at emitErrorCloseNT (internal/streams/destroy.js:74:3)<br>    at processTicksAndRejections (internal/process/task_queues.js:82:21)<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/oembed/server/server.ts:112:16<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/oembed/server/server.ts:170:10<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","errno":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","name":"FetchError"},"msg":"request to https://xxx.com/project/habinator-professionals/merge_requests/66 failed, reason: unable to verify the first certificate"} {"level":40,"time":"2023-04-18T15:19:39.906Z","pid":1,"hostname":"habinator-74cdb5b984-9xzmr","name":"OEmbed","msg":"OEmbed request size exceeded","url":"https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716"} 

{"level":50,"time":"2023-04-18T15:20:31.017Z","pid":1,"hostname":"habinator-74cdb5b984-9xzmr","name":"OEmbed","msg":"Error fetching url content","err":{"type":"FetchError","message":"request to https://xxx.com/project/habinator/commit/d6412356986fb0bf72ffad1281cf649cbfcc53a5 failed, reason: unable to verify the first certificate","stack":"FetchError: request to https://xxx.com/project/habinator/commit/d6412356986fb0bf72ffad1281cf649cbfcc53a5 failed, reason: unable to verify the first certificate<br>    at ClientRequest.<anonymous> (/app/bundle/programs/server/npm/node_modules/meteor/fetch/node_modules/node-fetch/lib/index.js:1444:11)<br>    at ClientRequest.emit (events.js:400:28)<br>    at ClientRequest.emit (domain.js:475:12)<br>    at TLSSocket.socketErrorListener (_http_client.js:475:9)<br>    at TLSSocket.emit (events.js:400:28)<br>    at TLSSocket.emit (domain.js:475:12)<br>    at emitErrorNT (internal/streams/destroy.js:106:8)<br>    at emitErrorCloseNT (internal/streams/destroy.js:74:3)<br>    at processTicksAndRejections (internal/process/task_queues.js:82:21)<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/oembed/server/server.ts:112:16<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40<br> => awaited here:<br>    at Function.Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)<br>    at app/oembed/server/server.ts:170:10<br>    at /app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40","errno":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","code":"UNABLE_TO_VERIFY_LEAF_SIGNATURE","name":"FetchError"},"msg":"request to https://xxx.com/project/habinator/commit/d6412356986fb0bf72ffad1281cf649cbfcc53a5 failed, reason: unable to verify the first certificate"}

Event name System Hook

{"level":50,"time":"2023-04-18T17:10:34.224Z","pid":1,"hostname":"habinator-74cdb5b984-9xzmr","name":"System","msg":"Exception while invoking method autoTranslate.getSupportedLanguages","err":{"type":"errorClass","message":"Auto-Translate is disabled [error-autotranslate-disabled]","stack":"Error: Auto-Translate is disabled [error-autotranslate-disabled]<br>    at MethodInvocation.autoTranslate.getSupportedLanguages (app/autotranslate/server/methods/getSupportedLanguages.ts:11:10)<br>    at MethodInvocation.methodsMap.<computed> (app/lib/server/lib/debug.js:74:34)<br>    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1902:12)<br>    at packages/ddp-server/livedata_server.js:1820:15<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)<br>    at packages/ddp-server/livedata_server.js:1818:36<br>    at new Promise (<anonymous>)<br>    at Server.applyAsync (packages/ddp-server/livedata_server.js:1817:12)<br>    at Server.apply (packages/ddp-server/livedata_server.js:1756:26)<br>    at Server.call (packages/ddp-server/livedata_server.js:1738:17)<br>    at Object.post (app/api/server/v1/misc.ts:554:27)<br>    at app/api/server/api.js:463:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9<br> => awaited here:<br>    at Promise.await (/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)<br>    at Server.apply (packages/ddp-server/livedata_server.js:1769:22)<br>    at Server.call (packages/ddp-server/livedata_server.js:1738:17)<br>    at Object.post (app/api/server/v1/misc.ts:554:27)<br>    at app/api/server/api.js:463:96<br>    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1329:12)<br>    at Object._internalRouteActionHandler [as action] (app/api/server/api.js:463:39)<br>    at Route._callEndpoint (packages/rocketchat_restivus/lib/route.coffee:150:32)<br>    at packages/rocketchat_restivus/lib/route.coffee:59:33<br>    at packages/simple_json-routes.js:100:9","isClientSafe":true,"error":"error-autotranslate-disabled","reason":"Auto-Translate is disabled","errorType":"Meteor.Error"},"msg":"Auto-Translate is disabled [error-autotranslate-disabled]"} 

Event name
Merge Request Hook
Event name Push Hook
Event name System Hook
Event name Push Hook`

**Comment by malko** [comment] 2023-04-19 09:57
What is weird is that the error occur whitout an event to be triggered firtst.
Also it doesn't seems to be related to push/mr events as I don't see error logs when they arrived.
I'll try to add some content verification to get rid of the error on edge cases, but I don't get the reason why you get the error in the first place => I'm a bit frustrated, and not confident that it will really fix the problem. Will push a new version today you will tell me.

**Comment by malko** [comment] 2023-04-19 09:59
Just to be sure, don't you have other hooks installed who may be responsible for the error ?

**Comment by TipiT** [comment] 2023-04-19 10:00
> Just to be sure, don't you have other hooks installed who may be responsible for the error ?

No, that is the only one. And it happens every time we push/merge.

Let me know if I can or should put some more console.loggins

**Comment by malko** [comment] 2023-04-19 10:02
> No, that is the only one. And it happens every time we push/merge.

Once again what is weird is that at the end of your logs I see:
```
Event name
Merge Request Hook
Event name Push Hook
Event name System Hook
Event name Push Hook
```
without errors between them

**Comment by malko** [comment] 2023-04-19 10:06
Also the split method is only called when dealing with System events which are only called when the "x-gitlab-event" header is equal to "System Hook'", and it doesn't seems that you have received any one of these.

**Comment by malko** [comment] 2023-04-19 10:10
Can you try to replace lines: 427,428 from:
```
		const event_name = data.event_name;
		const [, eventType] = data.event_name.split('_');
```
to 
```
		const event_name = data.event_name || '';
		const [, eventType] = event_name.split('_');
```

If this doesn't get rid of the error, it will be difficult for me to investigate more without a test environment.

**Comment by malko** [comment] 2023-04-19 10:19
If it doesn't get rid of the error getting sanitized content of the offending request may help:
=> change the line 102 from ```console.log('gitlabevent error', e);``` to ```console.log('gitlabevent error', e, request.content);``` and then send me log output (sanitized from sensible info)

And finally setting the IGNORE_ERROR_MESSAGES to true on line 7 should mute the error (but this won't fix it, obviously i would prefer to find the root cause and a fix)

**Comment by TipiT** [comment] 2023-04-19 10:27
I found the issue. I can set System Hooks (not webhooks) in GitLab for ALL projects/repos and webhooks for individual repos.

The error went away when I removed the system hook and set a webhook for every repo.


![gitlab-system-hook](https://user-images.githubusercontent.com/1223414/233047114-4b5627a0-ba57-46b3-827b-27380e5f2a3a.png)

**Comment by TipiT** [comment] 2023-04-19 10:28
Thanks a lot for helping out @malko !

**Comment by malko** [comment] 2023-04-19 10:30
Ok I'm happy we found the root cause !

**Closed as completed by malko** 2023-04-19 10:30 UTC
